### ISSUE TITLE
[Feature Request] Pandoc support

### ISSUE THREAD

**Issue by zyeri** [euclio/vim-markdown-composer#25]
I write a lot of CS/math notes using pandoc and it would be nice to be able to use this plugin to handle previewing.

Alternatively, if there would be some way for the current markdown engine to support raw LaTeX/TeX (I use equation/align/theorem/etc environments frequently), that would work just as well for me.

**Comment by euclio** [comment]
Ah, yes, I've been thinking about doing this. Hopefully I'll get some time to tackle it this weekend.

**Comment by Cutuchiqueno** [comment]
I would very much support the request for Pandoc. Pandoc flavoured markdown adds some very import syntax features for academic writing without loosing the easyness of markdown. Personally, I have written my whole PhD in Pandoc flavoured markdown. This would make this plugin so much more useful for me!

**Comment by euclio** [comment]
I have a prototype of this working, and, as I feared, it's really slow! I'll have to implement some sort of rate-limiting if you're using pandoc, I think.

**Comment by Cutuchiqueno** [comment]
that's great.

In pandoc performance also obviously depend on some set or unset parameters like creating citations. Thus, if the pandoc command will be configurable by the user he/she could influence the performance.

A configurable refresh-rate sounds good. I think it also worth to consider it apart from using pandoc. I created the #15 issue before. The problem in reall big buffers like the one mentioned up to the point that the plugin is not usable still is performance. When I open a buffer with around 30.000 words my CPU goes crazy. A sentence with 8-12 words needs around 20-30 seconds to be written in the preview because the plugin seems to re-render the whole preview after each keystroke. Maybe it could be a good solution to adapt the chunk that initiates a re-rendering process to the growing response time when buffers get bigger.

However, this discussion exceeds the scope of this ticket I fear.

**Comment by euclio** [comment]
@Cutuchiqueno That's very helpful. Here's what I'm thinking:

A `g:markdown_composer_refresh_rate` option, which allows you to specify the refresh rate in milliseconds. If not set or set to 0, the refresh will occur every keystroke by triggering an autocmd (current behavior). If the refresh rate is set, the autocmd will *not* be set up. Instead, a timer will send the markdown to the client at each refresh interval.

A `g:markdown_composer_external_command` option, that allows you to specify any external command to use for markdown rendering, assuming that the process will listen on stdin for markdown and output HTML on stdout. For example, to use pandoc, one might set `let g:markdown_composer_external_command="pandoc -f markdown -t html"`.

Does this seem reasonable?

The remaining question for me is how to properly support the `-s` option for pandoc. But maybe that's best left to a future issue.

**Comment by Cutuchiqueno** [comment]
@euclio thanks for this wonderful feature and sorry for my late response.

I tested it on my PhD (140.000 words) and it works well for review with a refresh rate of 5 seconds and without parsing bibliography.

I have two remarks as a feedback (if this is ok):

1. I proposed automatic modification of refresh rates before because I do not have something like a 'usual size' of markdown buffers as you phrase it in the docs. The size varies significantly from buffer to buffer and I can imagine that this might also be the case for many other persons.

2. I notice a flicker each time the website is updated when using an external command. I am on Chrome. Using a high refresh rate this can be quiete disturbing while reading the document. I haven't noticed the same if I use the plug-in's default html renderer.

Please do not take these points in a negative way. I am deeply grateful for this commit and it makes MarkdownComposer a lot more useful for me.

**Comment by euclio** [comment]
Thanks for the feedback. Would you mind opening a new issue? Glad the new
feature is useful.
