### ISSUE TITLE
Math mode fails for multiple symbols with a subscript and superscript in a single line

### ISSUE THREAD

**Issue by physicophilic** [euclio/vim-markdown-composer#89]
Firstly, I want to say that this plugin is amazing. 

There are some problems that I faced with it, but I am glad I have been able to work around them. Here is one of them:

In math mode, I often have to write complicated expressions like `\Gamma^{a}_{bc}` but I am facing a problem here. To illustrate:
```
$$
a^{b}_{c} a^{b}_{c}
$$
```
but

```
$$
\Gamma^{a}_{bc} \Gamma^{a}_{bc}
$$
```
doesn't.

I was able to find a work around to do this:

```
$$
\Gamma^a_{bc} \Gamma^a_{bc}
$$
```
which does get compiled properly. This may be a bug?

**Comment by euclio** [comment]
Thanks for the report. The Commonmark parser doesn't support math expressions directly, so the issue is that the first two expressions get their markup italicized before the KaTeX parser has a chance to see it.

There has been some discussion of adding true math support in raphlinus/pulldown-cmark#6, which would be ideal, but I have no idea when that feature will be complete.

**Comment by physicophilic** [comment]
Thanks for informing me. I guess I can live with this for now. Closing it.
